server:
  port: ${PORT:9000}

#server:
#  contextPath: /workflows-api

spring:
  application:
    name: workflow-api
  data:
    jpa:
      repositories:
        enabled: "true"
  jpa:
    hibernate:
      ddl-auto: "create"
      show_sql: true
      format_sql: true
    database-platform: "${SPRING_JPA_DATABASE_PLATFORM:org.hibernate.dialect.PostgreSQLDialect}"
  datasource:
    driverClassName: "${SPRING_DRIVER_CLASS_NAME:org.postgresql.Driver}"
    #change url accordingly
    #url: "${SPRING_DATASOURCE_URL:jdbc:postgresql://${POSTGRES_HOST:172.17.0.2}:5432/thingsboard}"
    url: "${SPRING_DATASOURCE_URL:jdbc:postgresql://${SPRING_DB_HOST:172.17.0.2}:5432/${SPRING_DB_NAME:thingsboard}}"
    #url: jdbc:postgresql://postgres:5432/thingsboard
    username: "${SPRING_DATASOURCE_USERNAME:postgres}"
    password: "${SPRING_DATASOURCE_PASSWORD:postgres}"

#for generating schema queries fired by hibernate
#spring.jpa.properties.javax.persistence.schema-generation.scripts.create-target: my-schema.sql
#spring.jpa.properties.javax.persistence.schema-generation.scripts.action: create


eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_SERVER_HOST:localhost}:8761/eureka/

install:
  data_dir: ${WORKFLOW_INSTALL_DIR:/home/akshay/IdeaProjects/HashmapAnalyticsFramework/workflow-api/src/main/resources/}
