
spring.application:
    name: functions-service

server:
  port: ${PORT:2222}

functions:
  input:
    location: "file://${FUNCTIONS_PATH:/Users/akshay/HAF/functionJars/}"

  output:
    #location: "file:///Users/akshay/HAF/functions"
    location: "file://${FUNCTIONS_OUTPUT_PATH:/home/}"
  protocol: "file"
  source:
    template: "task.vm"
  ignite:
    config: "cache.xml"

  #Other options are s3, ftp, ftps, https etc

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_SERVER_HOST:localhost}:8761/eureka/

# HSQLDB DAO Configuration
#spring:
#  data:
#    jpa:
#      repositories:
#        enabled: "true"
#  jpa:
#    hibernate:
#      ddl-auto: "create"
#      show_sql: true
#      format_sql: true
#    database-platform: "${SPRING_JPA_DATABASE_PLATFORM:org.hibernate.dialect.HSQLDialect}"
#  datasource:
#    driverClassName: "${SPRING_DRIVER_CLASS_NAME:org.hsqldb.jdbc.JDBCDriver}"
#    url: "${SPRING_DATASOURCE_URL:jdbc:hsqldb:file:${SQL_DATA_FOLDER:/tmp}/functions;sql.enforce_size=false}"
#    username: "${SPRING_DATASOURCE_USERNAME:sa}"
#    password: "${SPRING_DATASOURCE_PASSWORD:}"

spring:
  data:
    jpa:
      repositories:
        enabled: "true"
  jpa:
    hibernate:
      ddl-auto: "create"
      show_sql: true
      format_sql: true
    database-platform: "${SPRING_JPA_DATABASE_PLATFORM:org.hibernate.dialect.PostgreSQLDialect}"
  datasource:
    driverClassName: "${SPRING_DRIVER_CLASS_NAME:org.postgresql.Driver}"
    #change url accordingly
    url: "${SPRING_DATASOURCE_URL:jdbc:postgresql://${SPRING_DB_HOST:localhost}:5432/${SPRING_DB_NAME:thingsboard}}"
    username: "${SPRING_DATASOURCE_USERNAME:postgres}"
    password: "${SPRING_DATASOURCE_PASSWORD:postgres}"
